// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-lyYzX8jeMnt-6QztiNahSCxQE3oHy0',
    appId: '1:151030417665:web:88e94a14f0a56172b5b300',
    messagingSenderId: '151030417665',
    projectId: 'my-iot-health',
    authDomain: 'my-iot-health.firebaseapp.com',
    databaseURL: 'https://my-iot-health-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-health.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-A_ihrejX_sLbiA7qReZsBsWISRnEBIY',
    appId: '1:151030417665:android:d2ff54be2ff384a5b5b300',
    messagingSenderId: '151030417665',
    projectId: 'my-iot-health',
    databaseURL: 'https://my-iot-health-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-health.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBinNgdGpyGx4QtUSGcZmLle_pIRyLFhos',
    appId: '1:151030417665:web:c31bdcf0e27e4234b5b300',
    messagingSenderId: '151030417665',
    projectId: 'my-iot-health',
    authDomain: 'my-iot-health.firebaseapp.com',
    databaseURL: 'https://my-iot-health-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-health.appspot.com',
  );
}
